# version: 2
#
# build:
#   os: ubuntu-24.04
#   tools:
#     python: latest
#   jobs:
#     install:
#       - pip install --upgrade pip
#       - pip install -r requirements.txt
#     build:
#       html:
#         - zensical build --clean 
#     post_build:
#       - mkdir -p $READTHEDOCS_OUTPUT/html/
#       - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
#
version: 2

build:
   os: ubuntu-24.04
   tools:
      python: "3.13"
   jobs:
      pre_create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
      create_environment:
         - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
      install:
         - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen
