version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  image: latest

sphinx:
  configuration: conf.py

python:
  install:
    - method: pip
    - requirements_file: docs-requirements.txt
