version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    install:
      - uv add ephysiopy
    build:
      html:
        - zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
