site_name: ephysiopy

theme:
  name: "material"

repo_url: https://github.com/rhayman/ephysiopy

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
  - search

nav:
  - index.md
  - tutorials.md
  - how-to-guides.md
  - reference.md
  - explanation.md
