import matplotlib
import warnings
import functools
import matplotlib.pylab as plt
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from matplotlib.projections import get_projection_class
from matplotlib.collections import PatchCollection, LineCollection
from collections.abc import Callable
from inspect import getfullargspec
from matplotlib.patches import Rectangle
import numpy as np
import seaborn as sns
from ephysiopy.axona import tintcolours as tcols
from ephysiopy.common.utils import (
    clean_kwargs,
    BinnedData,
)

"""
This one allows us to save the
returned matplotlib Axis object to a location and name specified by the
user in the decorated function.

TODO: This should take in an axes which should gcf() and then save
as Axes are the thing that's returned from most of the functions below
"""


def saveFigure(func):
    """
    Decorator to save a plot generated by a function.

    Parameters
    ----------
    func : callable
        The function that generates the plot.

    Returns
    -------
    callable
        The wrapped function that saves the plot if 'save_as'
        is provided in kwargs.
    """

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        fig = func(*args, **kwargs)
        if fig is not None:
            if "save_as" in kwargs.keys():
                if kwargs["save_as"] is not None:
                    plt.savefig(kwargs["save_as"])
        return fig

    return wrapper


def stripAxes(func):
    """
    Decorator to strip the axes from a plot generated by a function.

    Parameters
    ----------
    func : callable
        The function that generates the plot.

    Returns
    -------
    callable
        The wrapped function that strips the axes from the plot.
    """

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        ax = func(*args, **kwargs)
        if ax is not None:
            plt.setp(ax.get_xticklabels(), visible=False)
            plt.setp(ax.get_yticklabels(), visible=False)
            ax.axes.get_xaxis().set_visible(False)
            ax.axes.get_yaxis().set_visible(False)
            if "polar" in ax.name:
                ax.set_rticks([])
            else:
                ax.spines["right"].set_visible(False)
                ax.spines["top"].set_visible(False)
                ax.spines["bottom"].set_visible(False)
                ax.spines["left"].set_visible(False)
        return ax

    return wrapper


@stripAxes
def _stripAx(ax):
    return ax


def addClusterChannelToAxes(func):
    """
    Decorator to add cluster and channel information to the axes of a plot.

    Parameters
    ----------
    func : callable
        The function that generates the plot.

    Returns
    -------
    callable
        The wrapped function that adds cluster and channel info to the axes.
    """
    argspec = getfullargspec(func)

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        ax = func(*args, **kwargs)
        if ax is not None:
            if "add_cluster" in kwargs.keys():
                if kwargs["add_cluster"] is True:
                    if "cluster" in argspec.args:
                        if len(args) == 3:
                            T, clust, chan = args
                        elif len(args) > 3:
                            T, clust, chan, rest = args
                        fig = ax.figure
                        fig.suptitle(f"Cluster: {clust} - Channel: {chan}")
        return ax

    return wrapper


def _add_colour_wheel(ax: plt.Axes, fig: plt.Figure, **kwargs) -> plt.Axes:
    """
    Adds a colour wheel to the axes

    Parameters
    ----------
    ax : plt.Axes
        The axes to add the colour wheel to.
    fig : plt.Figure
        The figure containing the axes.

    Returns
    -------
    plt.Axes
        The axes containing the colour wheel.
    """
    bbox = kwargs.get("bbox", (0.75, 0.75, 0.15, 0.15))
    ax_col = inset_axes(
        ax,
        width="100%",
        height="100%",
        bbox_to_anchor=bbox,
        axes_class=get_projection_class("polar"),
        bbox_transform=fig.transFigure,
    )
    ax_col.set_theta_zero_location("N")
    theta = np.linspace(0, 2 * np.pi, 1000)
    phi = np.linspace(0, 1, 2)
    X, Y = np.meshgrid(phi, theta)
    norm = matplotlib.colors.Normalize(0, 2 * np.pi)
    col_map = sns.color_palette("hsv", as_cmap=True)
    ax_col.pcolormesh(theta, phi, Y.T, norm=norm, cmap=col_map)
    ax_col.set_yticklabels([])
    ax_col.spines["polar"].set_visible(False)
    ax_col.set_rlim([-2.0, 1])
    ax_col.set_thetagrids([0, 90])
    return ax_col


# Taken from
# https://matplotlib.org/stable/gallery/lines_bars_and_markers/multicolored_line.html#sphx-glr-gallery-lines-bars-and-markers-multicolored-line-py


def colored_line(x, y, c, ax, **lc_kwargs):
    """
    Plot a line with a color specified along the line by a third value.

    It does this by creating a collection of line segments. Each line segment is
    made up of two straight lines each connecting the current (x, y) point to the
    midpoints of the lines connecting the current point with its two neighbors.
    This creates a smooth line with no gaps between the line segments.

    Parameters
    ----------
    x, y : array-like
        The horizontal and vertical coordinates of the data points.
    c : array-like
        The color values, which should be the same size as x and y.
    ax : Axes
        Axis object on which to plot the colored line.
    **lc_kwargs
        Any additional arguments to pass to matplotlib.collections.LineCollection
        constructor. This should not include the array keyword argument because
        that is set to the color argument. If provided, it will be overridden.

    Returns
    -------
    matplotlib.collections.LineCollection
        The generated line collection representing the colored line.
    """
    if "array" in lc_kwargs:
        warnings.warn('The provided "array" keyword argument will be overridden')

    # Default the capstyle to butt so that the line segments smoothly line up
    default_kwargs = {"capstyle": "butt"}
    default_kwargs.update(lc_kwargs)

    # Compute the midpoints of the line segments. Include the first and last points
    # twice so we don't need any special syntax later to handle them.
    x = np.asarray(x)
    y = np.asarray(y)
    x_midpts = np.hstack((x[0], 0.5 * (x[1:] + x[:-1]), x[-1]))
    y_midpts = np.hstack((y[0], 0.5 * (y[1:] + y[:-1]), y[-1]))

    # Determine the start, middle, and end coordinate pair of each line segment.
    # Use the reshape to add an extra dimension so each pair of points is in its
    # own list. Then concatenate them to create:
    # [
    #   [(x1_start, y1_start), (x1_mid, y1_mid), (x1_end, y1_end)],
    #   [(x2_start, y2_start), (x2_mid, y2_mid), (x2_end, y2_end)],
    #   ...
    # ]
    coord_start = np.column_stack((x_midpts[:-1], y_midpts[:-1]))[:, np.newaxis, :]
    coord_mid = np.column_stack((x, y))[:, np.newaxis, :]
    coord_end = np.column_stack((x_midpts[1:], y_midpts[1:]))[:, np.newaxis, :]
    segments = np.concatenate((coord_start, coord_mid, coord_end), axis=1)

    lc = LineCollection(segments, **default_kwargs)
    lc.set_array(c)  # set the colors of each segment

    return ax.add_collection(lc)


jet_cmap = matplotlib.colormaps["jet"]
grey_cmap = matplotlib.colormaps["gray_r"]


def _plot_multiple_clusters(
    func: Callable[..., plt.Figure], rmap: BinnedData, *args, **kwargs
) -> plt.Figure:
    """
    Plots multiple clusters.

    Parameters
    ----------
    func : function
        The function to apply to each cluster.
    rmap : BinnedData
        The rate map.
    **kwargs : dict
        Additional keyword arguments for the function.

    Returns
    -------
    matplotlib.figure.Figure
        The figure containing the plots.
    """
    fig = plt.figure()
    nrows = ncols = 1

    try:
        nrows = int(np.ceil((np.sqrt(len(rmap.binned_data)))))
        ncols = int(np.floor((np.sqrt(len(rmap.binned_data)))))
    except AttributeError:  # when rmap is not a BinnedData object
        nrows = int(np.ceil((np.sqrt(len(rmap)))))
        ncols = int(np.floor((np.sqrt(len(rmap)))))

    proj = kwargs.pop("projection", None)
    equal_axes = kwargs.pop("equal_axes", False)
    func2 = kwargs.pop("func2", None)

    for i, imap in enumerate(rmap):
        ax = fig.add_subplot(nrows, ncols, i + 1, projection=proj)
        # copy kwargs so that we don't modify the original
        kws = kwargs.copy()
        if "c" in kwargs.keys():
            kws["c"] = kwargs["c"][i]
        if func2:
            func2(imap, ax=ax, **kws)
        ax = func(imap, ax=ax, **kws)

        if equal_axes:
            ax.set_aspect("equal")
    return fig


@addClusterChannelToAxes
@stripAxes
def _plot_pcolormesh(rmap: BinnedData, ax: plt.Axes, **kwargs) -> plt.Axes:
    vmax = np.nanmax(np.ravel(rmap.binned_data))
    equal_axes = kwargs.pop("equal_axes", False)
    cmap = kwargs.pop("cmap", "viridis")  # matplotlib default
    kwargs = clean_kwargs(plt.pcolormesh, kwargs)
    # deal with 1-dimensional data - i.e. linear track
    if len(rmap.bin_edges) == 1:
        bin_edges = [np.array([0, 1, 3]), rmap.bin_edges[0]]
        binned_data = [np.tile(rmap.binned_data, (2, 1))]
    else:
        bin_edges = rmap.bin_edges
        binned_data = rmap.binned_data
    ax.pcolormesh(
        bin_edges[1],
        bin_edges[0],
        binned_data[0],
        edgecolors="face",
        vmax=vmax,
        cmap=cmap,
        shading="auto",
        **kwargs,
    )
    if equal_axes:
        ax.set_aspect(True)
    return ax


@addClusterChannelToAxes
@stripAxes
def _plot_patch_collection(xy: np.ma.MaskedArray, ax: plt.Axes, **kws) -> plt.Axes:
    """
    Plot a patch collection

    Parameters
    ----------
    xy : np.ndarray
        shape is [2  x m], where to put the rectangles

    **kwargs:
        ms - marker size for the rectangles
        c - array-like list or float of colour(s) for each rectangle

    Returns
    -------
    plt.Axes
        the axes into which the patches were plotted
    """
    # deal with possible nans
    xy = np.ma.masked_invalid(xy)
    equal_axes = kws.pop("equal_axes", False)
    tight_axes = kws.pop("tight_axes", False)
    rect_size = kws.pop("ms", 1)
    col = kws.pop("c", tcols.colours[1])
    col = np.array(col)
    if len(col) == 3:  # a singular value
        col = [col for _ in range(xy.shape[1])]

    kws_ = clean_kwargs(Rectangle, kws)
    rects = [
        Rectangle(
            _xy,
            width=rect_size,
            height=rect_size,
            # clip_box=ax.bbox,
            facecolor=_col.T,
            rasterized=True,
            **kws_,
        )
        for _xy, _col in zip(xy.T, col)
    ]
    ax.add_collection(PatchCollection(rects, match_original=True))
    if equal_axes:
        ax.set_aspect("equal")

    if tight_axes:
        ax.set_xlim(np.ma.min(xy[0, :]), np.ma.max(xy[0, :]))
        ax.set_ylim(np.ma.min(xy[1, :]), np.ma.max(xy[1, :]))

    return ax
